// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2VNWvg5I81Qb-A2rQXOl77cQzehV3ge4',
    appId: '1:318815881281:web:1957a2b2a641cacf215ec0',
    messagingSenderId: '318815881281',
    projectId: 'xrauth-e1436',
    authDomain: 'xrauth-e1436.firebaseapp.com',
    storageBucket: 'xrauth-e1436.appspot.com',
    measurementId: 'G-0HZKGVRYRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBliXO5ut7hYdvB31wy09J9h9uwk2cGyfI',
    appId: '1:318815881281:android:c8d81da97239d5b1215ec0',
    messagingSenderId: '318815881281',
    projectId: 'xrauth-e1436',
    storageBucket: 'xrauth-e1436.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiUeOM5QLfOnw08vG5w_KoF6eO4HrzVRg',
    appId: '1:318815881281:ios:4b207e8b9c3c6a87215ec0',
    messagingSenderId: '318815881281',
    projectId: 'xrauth-e1436',
    storageBucket: 'xrauth-e1436.appspot.com',
    androidClientId: '318815881281-lbs8ifdhev1qgrqscc7eq347j2574e2j.apps.googleusercontent.com',
    iosClientId: '318815881281-38fgc9drp4838h65bs5su82hcv675jpn.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthentication',
  );
}
